# Generated by Django 5.2.8 on 2025-11-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
