# Generated by Django 5.2.8 on 2025-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_materia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='cantidad_alumnos',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
